version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dony_pizza
      MYSQL_USER: dony
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
